export const countryCodes: { [country: string]: string } = {
    "Australia": "au",
    "Austria": "at",
    "Bahrain": "bh",
    "Belgium": "be",
    "Brazil": "br",
    "Canada": "ca",
    "China": "cn",
    "France": "fr",
    "Germany": "de",
    "Hungary": "hu",
    "Italy": "it",
    "Japan": "jp",
    "Malaysia": "my",
    "Mexico": "mx",
    "Monaco": "mc",
    "Netherlands": "nl",
    "Russia": "ru",
    "Singapore": "sg",
    "Spain": "es",
    "United Kingdom": "gb",
    "UK": "gb",
    "United States": "us",
    "USA": "us",
    "United Arab Emirates": "ae",
    "UAE": "ae",
    "South Africa": "za",
    "Turkey": "tr",
    "India": "in",
    "South Korea": "kr",
    "Azerbaijan": "az",
    "Saudi Arabia": "sa",
    "Czech Republic": "cz",
    "Morocco": "ma",
    "Portugal": "pt",
    "Finland": "fi",
    "Switzerland": "ch",
    "Luxembourg": "lu",
    "San Marino": "sm",
    "Malta": "mt",
    "Andorra": "ad",
    "Qatar": "qa"
  };